#!/bin/sh

rocm-smi -d 0 --setsclk 3
sleep 2
rocm-smi -d 0 -g

./rocblas_sgemm_example -m1760 -n16 -k1760 -tNN -ov -fy
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1760 -n32 -k1760 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1760 -n64 -k1760 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1760 -n128 -k1760 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1760 -n7000 -k1760 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2048 -n16 -k2048 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2048 -n32 -k2048 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2048 -n64 -k2048 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2048 -n128 -k2048 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2048 -n7000 -k2048 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2560 -n16 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2560 -n32 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2560 -n64 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2560 -n128 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2560 -n7000 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4096 -n16 -k4096 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4096 -n32 -k4096 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4096 -n64 -k4096 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4096 -n128 -k4096 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4096 -n7000 -k4096 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1760 -n16 -k1760 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1760 -n32 -k1760 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1760 -n64 -k1760 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1760 -n128 -k1760 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1760 -n7000 -k1760 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2048 -n16 -k2048 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2048 -n32 -k2048 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2048 -n64 -k2048 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2048 -n128 -k2048 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2048 -n7000 -k2048 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2560 -n16 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2560 -n32 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2560 -n64 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2560 -n128 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2560 -n7000 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4096 -n16 -k4096 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4096 -n32 -k4096 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4096 -n64 -k4096 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4096 -n128 -k4096 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4096 -n7000 -k4096 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1760 -n7133 -k1760 -tNT -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2048 -n7133 -k2048 -tNT -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m2560 -n7133 -k2560 -tNT -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4096 -n7133 -k4096 -tNT -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m5124 -n9124 -k1760 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m35 -n8457 -k1760 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m5124 -n9124 -k2048 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m35 -n8457 -k2048 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m5124 -n9124 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m35 -n8457 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m5124 -n9124 -k4096 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m35 -n8457 -k4096 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m5124 -n9124 -k1760 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m35 -n8457 -k1760 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m5124 -n9124 -k2048 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m35 -n8457 -k2048 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m5124 -n9124 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m35 -n8457 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m5124 -n9124 -k4096 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m35 -n8457 -k4096 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m7680 -n16 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m7680 -n32 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m7680 -n64 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m7680 -n128 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m7680 -n16 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m7680 -n32 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m7680 -n64 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m7680 -n128 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m3072 -n16 -k1024 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m3072 -n32 -k1024 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m3072 -n64 -k1024 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m3072 -n128 -k1024 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m3072 -n16 -k1024 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m3072 -n32 -k1024 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m3072 -n64 -k1024 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m3072 -n128 -k1024 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m3072 -n7435 -k1024 -tNT -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m7680 -n5481 -k2560 -tNT -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n8 -k500000 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n8 -k500000 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n16 -k500000 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n16 -k500000 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n8 -k500000 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n8 -k500000 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n16 -k500000 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n16 -k500000 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n700 -k512 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n700 -k512 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m7680 -n24000 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m6144 -n24000 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4608 -n24000 -k1536 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m8448 -n24000 -k2816 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m3072 -n24000 -k1024 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m7680 -n48000 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m6144 -n48000 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4608 -n48000 -k1536 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m8448 -n48000 -k2816 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m3072 -n48000 -k1024 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m7680 -n24000 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m6144 -n24000 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4608 -n24000 -k1536 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m8448 -n24000 -k2816 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m3072 -n24000 -k1024 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m7680 -n48000 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m6144 -n48000 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4608 -n48000 -k1536 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m8448 -n48000 -k2816 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m3072 -n48000 -k1024 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m6144 -n16 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4608 -n16 -k1536 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m8448 -n16 -k2816 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m6144 -n32 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4608 -n32 -k1536 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m8448 -n32 -k2816 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m6144 -n16 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4608 -n16 -k1536 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m8448 -n16 -k2816 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m6144 -n32 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m4608 -n32 -k1536 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m8448 -n32 -k2816 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n24000 -k2816 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n24000 -k2048 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n24000 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n24000 -k1536 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n24000 -k2816 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n24000 -k2048 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n24000 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n24000 -k1536 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n16 -k512 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n16 -k512 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n24000 -k2816 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n24000 -k2048 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n24000 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n24000 -k1536 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n24000 -k2816 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n24000 -k2048 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n24000 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n24000 -k1536 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n16 -k512 -tNT -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n16 -k512 -tNT -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n48000 -k2816 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n48000 -k2048 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n48000 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n48000 -k1536 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n48000 -k2816 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n48000 -k2048 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n48000 -k2560 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n48000 -k1536 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n32 -k512 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n32 -k512 -tNN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n48000 -k2816 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n48000 -k2048 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n48000 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n48000 -k1536 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n48000 -k2816 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n48000 -k2048 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n48000 -k2560 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n48000 -k1536 -tTN -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m512 -n32 -k512 -tNT -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
./rocblas_sgemm_example -m1024 -n32 -k512 -tNT -ov -fn
rocm-smi -c | grep "GPU Clock Level"
rocm-smi -d 0 --setsclk 7 > /dev/null
